# Generated by Django 6.0.7 on 2026-08-13 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_checklistitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'permissions': [('can_share_public_notes', 'Can share notes publicly')]},
        ),
    ]
